---
exclude_paths:
  - "www/js/moment/**"
  - "lib*/**"
  - "**/*README.md"
  - "www/thirdPartyLibrary/**/*"
  - "www/js/handsontable-6.2.2/**/*"
  - ".phpunit.result.cache"
  - "backup/**/*"
  - "*[\.-]min\.css"
  - "*[\.-]min\.js"
  - "**/*node_modules/.*"
  - "*bower_components/.*"
  - "*vendor/.*"
  - "*third[_-]?[Pp]arty/.*"
  - "*samples?/.*"
  - "*releases?/.*"
  - "*builds?/.*"
  - "*dist/.*"
  - "*external/.*"
  - "*libs/.*"
  - "*d3\.js"
  - "*angular(-resource|)?\.js"
  - "*select2(-resource|)?\.js"
  - "*-ace\.js"
  - "*typeahead\.js"
  - "*jquery-ui\.js"
  - "*reveal\.js"
  - "*three\.js"
  - "*chart\.js"
  - "*jquery\.js"
  - "*underscore\.js"
  - "*lodash\.js"
  - "*bootstrap\.js"
  - "*bootstrap\.css"
  - "*font-awesome\.css"
  - "*\.[Dd]esigner\.cs"
